name: Build and Publish
on:
  push:
    paths:
        - "package.json"

env:
  GIT: 'true'
  GITURL: 'https://github.com/Sirherobrine23/APT_bysh23'
  GITBRANCH: master
  GITUSER: Sirherobrine23
  GITPASS: ${{ secrets.PASS }}
  GITDIR: 'package/main'
  
jobs:
  Node:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Node install
        env:
          DEBIAN_FRONTEND: noninteractive 
        run: |
          sudo apt update
          sudo apt install -y nodejs npm

      - name: Electron Build
        run: |
          npm install
          npm run build-deb

      - name: Gerando Tag
        id: tag
        run: |
          echo ::set-env name=RELEASE_NAME::"$(TZ=UTC+3 date +"%d/%m/%Y")-Push-Commit"
          echo ::set-env name=RELEASE_TAG::"$(TZ=UTC+3 date +"%d/%m/%Y")"
          echo "Versão pós commit, só para testes, de build" >> release.txt
      
      - name: Publicando
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.FILE_NAME }}
          files: dist/*.deb
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: release.txt
